# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    draw_creator:
        class: AppBundle\Service\DrawCreator
        arguments: ['@doctrine.orm.entity_manager']

    group_creator:
        class: AppBundle\Service\GroupCreator
        arguments: ['@doctrine.orm.entity_manager']

    ranking_builder:
        class: AppBundle\Service\RankingBuilder
        arguments: ['@doctrine.orm.entity_manager']