championathasplayer_index:
    path:     /
    defaults: { _controller: "AppBundle:ChampionatHasPlayer:index" }
    methods:  GET

championathasplayer_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:ChampionatHasPlayer:show" }
    methods:  GET

championathasplayer_new:
    path:     /new
    defaults: { _controller: "AppBundle:ChampionatHasPlayer:new" }
    methods:  [GET, POST]

championathasplayer_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:ChampionatHasPlayer:edit" }
    methods:  [GET, POST]

championathasplayer_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:ChampionatHasPlayer:delete" }
    methods:  DELETE
