draw_index:
    path:     /
    defaults: { _controller: "AppBundle:Draw:index" }
    methods:  GET

draw_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Draw:show" }
    methods:  GET

draw_new:
    path:     /new
    defaults: { _controller: "AppBundle:Draw:new" }
    methods:  [GET, POST]

draw_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Draw:edit" }
    methods:  [GET, POST]

draw_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Draw:delete" }
    methods:  DELETE
